### ISSUE TITLE
don't use network_mode host

### ISSUE THREAD

**Issue by untzag** [wright-group/bluesky-in-a-box#3]
Using network_mode: host defeats the point of network isolation, one of the main ideas of containerization. We are currently stuck using this network_mode because our dependencies make some bad assumptions.

- re-manager assumes redis is running locally
- queueserver assumes re-manager is running locally

If our dependencies respected environment variables for the ip:host of these services, we could properly use internal networks and have a much cleaner setup.

This is not a big issue at this time. In practice I don't actually expect to see port collision due to lack of isolation.

**Comment by ksunden** [comment]
I believe this is closed here (we have not made this change on wright-fakes yet, but I think we have everything here)
