### ISSUE TITLE
Startup problems when certain hardware is busy on starting containers

### ISSUE THREAD

**Issue by ksunden** [wright-group/bluesky-in-a-box#32]
startup seems to hang when in particular triggered sensors are busy at start up... Not fully sure if it is actually due to the daemons themselves misbehaving or what.

Noticed on waldo with the daq and on the fs machine with the array detector and daq.

Restarting the daemons resolved the problem, which makes me wonder if the root cause is daemons being stuck, but I still think we should if possible unstick ourselves...

This may actually be a yaqc-bluesky problem, not here, but annotating here because this is the context it was discovered in and don't have time to narrow in right this second

**Comment by untzag** [comment]
> non-triggered sensors

Sensors not implementing `has-measure-trigger`? So the mqtt sensor?

**Comment by ksunden** [comment]
Oops, I meant triggered sensors, those implementing has-measure-trigger

**Comment by untzag** [comment]
This might be a red herring, but consider that triggered sensors might not have populated channel names etc until they measure the first time.

**Comment by ksunden** [comment]
Fixed by bluesky/yaqc-bluesky#85

We have ensured that sensors have channel info at startup, and no longer have a wait until still at startup
